### ISSUE TITLE
[BUG] Структура файла расписания изменилась

### ISSUE THREAD

**Issue by mllightitup** [mirea-ninja/rtu-mirea-schedule#31]
**Описание ошибки**
Кажется они поменяли структуру файла расписания. Теперь на каждой странице в файле по 2 группы. Если я не ошибаюсь, раньше была одна страница со всеми группами.

**Скриншоты или видео**
![image](https://user-images.githubusercontent.com/43480503/187576584-698e2498-968b-4670-a0be-d3915faf8973.png)

**Дополнительный текст**
Наверное нужно обновить способ парсинга файла

**Comment by 0niel** [comment]
Исправлено. Спасибо.
